2018-10-23 19:41:17 [scrapy] DEBUG: Retrying <GET https://www.tokopedia.com/robots.txt> (failed 1 times): DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
2018-10-23 19:41:17 [scrapy] DEBUG: Retrying <GET https://www.tokopedia.com/robots.txt> (failed 2 times): DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
2018-10-23 19:41:17 [scrapy] DEBUG: Gave up retrying <GET https://www.tokopedia.com/robots.txt> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
2018-10-23 19:41:17 [scrapy] ERROR: Error downloading <GET https://www.tokopedia.com/robots.txt>: DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/anaconda2/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/anaconda2/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 954, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
DNSLookupError: DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
2018-10-23 19:41:17 [scrapy] DEBUG: Retrying <GET https://www.tokopedia.com/pondok-apple/termurah-bergaransi-bnib-ipad-mini-4-128gb-wi-fi-cellular-garansi?trkid=f=Ca0000L000P0W0S0Sh00Co0Po0Fr0Cb0_src=other-product_page=1_ob=32_q=_po=2_catid=276> (failed 1 times): DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
2018-10-23 19:41:17 [scrapy] DEBUG: Retrying <GET https://www.tokopedia.com/pondok-apple/termurah-bergaransi-bnib-ipad-mini-4-128gb-wi-fi-cellular-garansi?trkid=f=Ca0000L000P0W0S0Sh00Co0Po0Fr0Cb0_src=other-product_page=1_ob=32_q=_po=2_catid=276> (failed 2 times): DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
2018-10-23 19:41:17 [scrapy] DEBUG: Gave up retrying <GET https://www.tokopedia.com/pondok-apple/termurah-bergaransi-bnib-ipad-mini-4-128gb-wi-fi-cellular-garansi?trkid=f=Ca0000L000P0W0S0Sh00Co0Po0Fr0Cb0_src=other-product_page=1_ob=32_q=_po=2_catid=276> (failed 3 times): DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
2018-10-23 19:41:17 [scrapy] ERROR: Error downloading <GET https://www.tokopedia.com/pondok-apple/termurah-bergaransi-bnib-ipad-mini-4-128gb-wi-fi-cellular-garansi?trkid=f=Ca0000L000P0W0S0Sh00Co0Po0Fr0Cb0_src=other-product_page=1_ob=32_q=_po=2_catid=276>
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/anaconda2/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/anaconda2/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 954, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
DNSLookupError: DNS lookup failed: no results for hostname lookup: www.tokopedia.com.
2018-10-23 19:41:18 [scrapy] INFO: Closing spider (finished)
2018-10-23 19:41:18 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 6,
 'downloader/exception_type_count/twisted.internet.error.DNSLookupError': 6,
 'downloader/request_bytes': 1830,
 'downloader/request_count': 6,
 'downloader/request_method_count/GET': 6,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 23, 12, 41, 18, 43020),
 'log_count/DEBUG': 6,
 'log_count/ERROR': 2,
 'log_count/INFO': 6,
 'memusage/max': 54833152,
 'memusage/startup': 54833152,
 'retry/count': 4,
 'retry/max_reached': 2,
 'retry/reason_count/twisted.internet.error.DNSLookupError': 4,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'start_time': datetime.datetime(2018, 10, 23, 12, 41, 17, 635815)}
2018-10-23 19:41:18 [scrapy] INFO: Spider closed (finished)
